# Enables the "Sponsor" button on the GitHub repo.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: dilmun

# Uncomment / fill in any others you use:
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# custom: ["https://paypal.me/your-handle"]
